[package]
name = "dalfox"
version = "3.0.0-dev.1"
edition = "2024"
authors = ["hahwul"]
description = "Dalfox is a powerful open-source XSS scanner and utility focused on automation"
license = "MIT"

[dependencies]
clap = { version = "4.0", features = ["derive", "env"] }
url = "2.0"
reqwest = "0.11"
scraper = "0.18"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indicatif = "0.17"
urlencoding = "2.1"
base64 = "0.21"
chrono = "0.4"
toml = "0.8"
axum = "0.7"
sha2 = "0.10"
hex = "0.4"
regex = "1"
atty = "0.2"
rmcp = { version = "0.8.0", features = ["server", "macros"] }
schemars = { version = "0.8", features = ["derive"] }
