[package]
name = "dalfox"
version = "3.0.0-alpha.1"
edition = "2024"
authors = ["hahwul"]
description = "Dalfox is a powerful open-source XSS scanner and utility focused on automation"
license = "MIT"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
url = "2.0"
reqwest = "0.11"
scraper = "0.18"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indicatif = "0.17"
urlencoding = "2.1"
base64 = "0.21"
