// Fallback parameter-name wordlist used when no `--mining-dict-word` /
// `--remote-wordlists` source is supplied. Seeded from
// https://github.com/1ndianl33t/Gf-Patterns/blob/master/xss.json and extended
// with high-signal reflected-input parameter names drawn from common
// param-mining corpora (Arjun / param-miner / SecLists) — redirect &
// return-URL params (frequent reflected-XSS / open-redirect sinks), free-text
// fields (title/message/comment/description), view/format/template selectors,
// and identity/locale fields. Kept de-duplicated and ordered most-common-first
// so the EWMA collapse heuristic and any name cap still see the highest-value
// names early.
pub const GF_PATTERNS_PARAMS: &[&str] = &[
    // --- original gf-patterns xss.json seed ---
    "q",
    "s",
    "search",
    "lang",
    "keyword",
    "query",
    "page",
    "keywords",
    "year",
    "view",
    "email",
    "type",
    "name",
    "p",
    "callback",
    "jsonp",
    "api_key",
    "api",
    "password",
    "emailto",
    "token",
    "username",
    "csrf_token",
    "unsubscribe_token",
    "id",
    "item",
    "page_id",
    "month",
    "immagine",
    "list_type",
    "url",
    "terms",
    "categoryid",
    "key",
    "l",
    "begindate",
    "enddate",
    // --- redirect / return-URL family (reflected-XSS + open-redirect sinks) ---
    "redirect",
    "redirect_uri",
    "redirect_url",
    "redirecturl",
    "redir",
    "return",
    "returnurl",
    "return_url",
    "returnto",
    "return_to",
    "next",
    "continue",
    "goto",
    "dest",
    "destination",
    "target",
    "to",
    "out",
    "u",
    "uri",
    "link",
    "ref",
    "referrer",
    "referer",
    "back",
    "backurl",
    "checkout_url",
    "success_url",
    "cancel_url",
    "image_url",
    "domain",
    "host",
    // --- free-text / reflected-content fields ---
    "title",
    "subject",
    "message",
    "msg",
    "body",
    "comment",
    "content",
    "text",
    "description",
    "desc",
    "note",
    "data",
    "value",
    "input",
    "tag",
    "tags",
    "label",
    "caption",
    "summary",
    "feedback",
    "reason",
    "error",
    "error_description",
    "err",
    "status",
    "info",
    "alert",
    "notice",
    // --- view / format / template selectors ---
    "mode",
    "action",
    "format",
    "output",
    "template",
    "theme",
    "style",
    "sort",
    "order",
    "orderby",
    "filter",
    "category",
    "cat",
    "tab",
    "section",
    "step",
    "state",
    "color",
    // --- identity / locale / misc ---
    "user",
    "userid",
    "user_id",
    "uid",
    "account",
    "profile",
    "nick",
    "nickname",
    "firstname",
    "lastname",
    "fullname",
    "display",
    "locale",
    "country",
    "region",
    "city",
    "date",
    "time",
    "day",
    "week",
    "from",
    "code",
    "file",
    "filename",
    "path",
    "dir",
    "folder",
    "preview",
    "debug",
    "test",
];

#[cfg(test)]
mod tests;
