# Snapshot persistence + generated-block rendering for the `scripts/` harnesses.
#
# Every measuring harness follows the same shape: produce a JSON snapshot under
# `docs/data/`, compare it against the committed one to decide whether anything
# regressed, and (optionally) re-render a marker-delimited block inside a docs
# page. That shape lives here so the harnesses only supply the numbers.

require "json"
require "file_utils"

module Snapshot
  # Read a committed snapshot, or nil when it does not exist yet.
  def self.load(path : String) : JSON::Any?
    return nil unless File.exists?(path)
    JSON.parse(File.read(path))
  rescue
    nil
  end

  # Write a snapshot, creating parent directories. Always ends with a newline
  # so the file is diff-friendly.
  def self.write(path : String, data)
    FileUtils.mkdir_p(File.dirname(path))
    json = data.is_a?(JSON::Any) ? data.to_pretty_json : JSON.parse(data.to_json).to_pretty_json
    File.write(path, json + "\n")
    puts "==> wrote #{path}"
  end

  # Standard provenance header every snapshot carries. Harnesses merge this
  # into their own payload so the JSON files stay comparable.
  def self.stamp(tool : String, dalfox_version : String, extra = nil) : Hash(String, JSON::Any)
    base = {
      "generated_at"   => JSON::Any.new(Time.utc.to_s("%Y-%m-%dT%H:%M:%SZ")),
      "tool"           => JSON::Any.new(tool),
      "dalfox_version" => JSON::Any.new(dalfox_version),
    }
    if extra
      JSON.parse(extra.to_json).as_h.each { |k, v| base[k] = v }
    end
    base
  end

  # ---------------------------------------------------------------------------
  # Regression gating.
  # ---------------------------------------------------------------------------

  # One metric compared against its committed value.
  struct Delta
    getter name : String
    getter before : Float64?
    getter after : Float64
    getter tolerance : Float64
    getter higher_is_better : Bool

    def initialize(@name, @before, @after, @tolerance, @higher_is_better)
    end

    def change : Float64?
      @before.try { |b| @after - b }
    end

    # A regression is a move in the bad direction by more than `tolerance`.
    def regressed? : Bool
      c = change
      return false unless c
      @higher_is_better ? c < -@tolerance : c > @tolerance
    end

    def improved? : Bool
      c = change
      return false unless c
      @higher_is_better ? c > @tolerance : c < -@tolerance
    end

    def to_s(io : IO)
      b = @before
      io << "  " << (regressed? ? "REGRESSED" : (improved? ? "improved " : "ok       ")) << " "
      io << @name << ": "
      if b
        io << b.round(2) << " -> " << @after.round(2)
        c = change.not_nil!
        io << " (" << (c >= 0 ? "+" : "") << c.round(2) << ")"
      else
        io << @after.round(2) << " (no baseline)"
      end
    end
  end

  # Compare `after` against the committed snapshot for a set of metrics.
  #
  # `metrics` maps a dotted path inside the snapshot (`"total.rate"`) to the
  # tolerance and direction. Returns every delta; the caller decides what to do
  # with the regressed ones.
  def self.compare(before : JSON::Any?,
                   after : JSON::Any,
                   metrics : Hash(String, {Float64, Bool})) : Array(Delta)
    metrics.map do |path, spec|
      tolerance, higher_is_better = spec
      Delta.new(path, dig_f(before, path), dig_f(after, path) || 0.0, tolerance, higher_is_better)
    end
  end

  # Dotted-path lookup returning a Float64 when the value is numeric.
  def self.dig_f(data : JSON::Any?, path : String) : Float64?
    node = data
    return nil unless node
    path.split('.').each do |seg|
      node = if idx = seg.to_i?
               node.as_a?.try(&.[idx]?)
             else
               node.as_h?.try(&.[seg]?)
             end
      return nil unless node
    end
    node.as_f? || node.as_i?.try(&.to_f)
  end

  # ---------------------------------------------------------------------------
  # Docs rendering.
  # ---------------------------------------------------------------------------

  # Replace the block delimited by `<!-- TAG:BEGIN … -->` / `<!-- TAG:END -->`
  # inside a docs page. Aborts when the markers are missing rather than
  # silently appending — a moved marker should be loud.
  def self.render_block(page_path : String, tag : String, refresh_cmd : String, body : String)
    abort "missing page: #{page_path}" unless File.exists?(page_path)
    begin_marker = "<!-- #{tag}:BEGIN — generated by `#{refresh_cmd}`; do not edit by hand -->"
    end_marker = "<!-- #{tag}:END -->"
    content = File.read(page_path)
    unless content.includes?("<!-- #{tag}:BEGIN")
      abort "markers not found in #{page_path}; expected #{begin_marker} ... #{end_marker}"
    end
    block = "#{begin_marker}\n\n#{body}\n#{end_marker}"
    replaced = content.sub(/<!-- #{Regex.escape(tag)}:BEGIN[\s\S]*?#{Regex.escape(end_marker)}/, block)
    File.write(page_path, replaced)
    puts "==> wrote #{page_path}"
  end

  # ---------------------------------------------------------------------------
  # Shared docs styling. The docs site is dark-only with the navy/periwinkle
  # palette; these mirror the tokens `xssmaze.md` already renders against so
  # every generated block looks like it belongs to the same page.
  # ---------------------------------------------------------------------------

  SUCCESS = "#34d399"
  ACCENT  = "#8b94e8"
  WARN    = "#f59e0b"
  DANGER  = "#f87171"

  # Rate → palette colour, worst-first thresholds.
  def self.rate_color(rate : Float64) : String
    case
    when rate >= 90 then SUCCESS
    when rate >= 70 then ACCENT
    when rate >= 40 then WARN
    else                 DANGER
    end
  end

  # Flat metric tile matching the XSSMaze score page.
  def self.tile(label : String, value : String, sub : String = "",
                value_color : String = "var(--text-primary,#e7e9f3)") : String
    String.build do |io|
      io << %(<div style="padding:.85rem 1rem;background:var(--bg-surface,#11141f);border:1px solid var(--border-light,#222741);border-radius:10px">)
      io << %(<div style="font-size:.7rem;font-weight:600;text-transform:uppercase;letter-spacing:.08em;color:var(--text-muted,#636980)">#{label}</div>)
      io << %(<div style="margin-top:.3rem;font-size:1.5rem;font-weight:700;line-height:1;color:#{value_color};font-variant-numeric:tabular-nums">#{value}</div>)
      io << %(<div style="margin-top:.35rem;font-size:.75rem;color:var(--text-secondary,#9aa0bb)">#{sub}</div>) unless sub.empty?
      io << %(</div>)
    end
  end

  # Responsive grid wrapper for `tile` output.
  def self.tiles(html : String) : String
    %(<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(9rem,1fr));gap:.75rem;margin:1rem 0">#{html}</div>)
  end
end
