#!/bin/bash
PROJDIR=$(cd `dirname $0`/.. && pwd)

VERSION="${1}"
TAG="v${VERSION}"
USER="hahwul"
REPO="dalfox"
BINARY="${REPO}"

if [[ -z "${VERSION}" ]]; then
    echo "Usage: ${0} <version>"
    exit 1
fi

cd ${PROJDIR}

# Run the tests
go test
if [ $? -ne 0 ]; then
    echo "Tests failed. Aborting."
    exit 3
fi


# Check if tag exists
git fetch --tags
git tag | grep "^${TAG}$"

for ARCH in "amd64" "386"; do
    for OS in "darwin" "linux" "windows" "freebsd"; do

        BINFILE="${BINARY}"

        if [[ "${OS}" == "windows" ]]; then
            BINFILE="${BINFILE}.exe"
        fi

        rm -f ${BINFILE}

        GOOS=${OS} GOARCH=${ARCH} go build github.com/${USER}/${REPO}

        if [[ "${OS}" == "windows" ]]; then
            ARCHIVE="${BINARY}-${OS}-${ARCH}-${VERSION}.zip"
            zip ${ARCHIVE} ${BINFILE}
	    cp ${BINFILE} ${BINARY}_${OS}_${ARCH}
        else
            ARCHIVE="${BINARY}-${OS}-${ARCH}-${VERSION}.tgz"
            tar --create --gzip --file=${ARCHIVE} ${BINFILE}
	    cp ${BINFILE} ${BINARY}_${OS}_${ARCH}
        fi
    done
done

