package scanning

//GetEventHandlers is return event handlers (array type)
func GetEventHandlers() []string {
	handlers := []string{
		"onabort",
		"onactivate",
		"onafterprint",
		"onafterscriptexecute",
		"onafterupdate",
		"onanimationcancel",
		"onanimationstart",
		"onauxclick",
		"onbeforeactivate",
		"onbeforecopy",
		"onbeforecut",
		"onbeforedeactivate",
		"onbeforeeditfocus",
		"onbeforepaste",
		"onbeforeprint",
		"onbeforescriptexecute",
		"onbeforeunload",
		"onbeforeupdate",
		"onbegin",
		"onblur",
		"onbounce",
		"oncanplay",
		"oncanplaythrough",
		"oncellchange",
		"onchange",
		"onclick",
		"oncontextmenu",
		"oncontrolselect",
		"oncopy",
		"oncut",
		"ondataavailable",
		"ondatasetchanged",
		"ondatasetcomplete",
		"ondblclick",
		"ondeactivate",
		"ondrag",
		"ondragdrop",
		"ondragend",
		"ondragenter",
		"ondragleave",
		"ondragover",
		"ondragstart",
		"ondrop",
		"onend",
		"onerror",
		"onerrorupdate",
		"onfilterchange",
		"onfinish",
		"onfocus",
		"onfocusin",
		"onfocusout",
		"onhashchange",
		"onhelp",
		"oninput",
		"oninvalid",
		"onkeydown",
		"onkeypress",
		"onkeyup",
		"onlayoutcomplete",
		"onload",
		"onloadend",
		"onloadstart",
		"onloadstart",
		"onlosecapture",
		"onmediacomplete",
		"onmediaerror",
		"onmessage",
		"onmousedown",
		"onmouseenter",
		"onmouseleave",
		"onmousemove",
		"onmouseout",
		"onmouseover",
		"onmouseup",
		"onmousewheel",
		"onmove",
		"onmoveend",
		"onmovestart",
		"onoffline",
		"ononline",
		"onoutofsync",
		"onpageshow",
		"onpaste",
		"onpause",
		"onplay",
		"onplaying",
		"onpointerdown",
		"onpointerenter",
		"onpointerleave",
		"onpointermove",
		"onpointerout",
		"onpointerover",
		"onpointerup",
		"onpopstate",
		"onprogress",
		"onpropertychange",
		"onreadystatechange",
		"onredo",
		"onrepeat",
		"onreset",
		"onresize",
		"onresizeend",
		"onresizestart",
		"onresume",
		"onreverse",
		"onrowdelete",
		"onrowexit",
		"onrowinserted",
		"onrowsenter",
		"onscroll",
		"onsearch",
		"onseek",
		"onselect",
		"onselectionchange",
		"onselectstart",
		"onstart",
		"onstop",
		"onstorage",
		"onsubmit",
		"onsyncrestored",
		"ontimeerror",
		"ontimeupdate",
		"ontoggle",
		"ontouchend",
		"ontouchmove",
		"ontouchstart",
		"ontrackchange",
		"ontransitioncancel",
		"ontransitionend",
		"ontransitionrun",
		"onundo",
		"onunhandledrejection",
		"onunload",
		"onurlflip",
		"onvolumechange",
		"onwaiting",
		"onwheel",
		"whatthe=\"'onload",
		"onpointerrawupdate",
	}
	return handlers
}

// GetTags is return tag list (array type)
func GetTags() []string {
	tags := []string{
		"script",
		"iframe",
		"svg",
		"img",
		"video",
		"audio",
		"meta",
		"object",
		"embed",
		"style",
		"frame",
		"frameset",
		"applet",
	}
	return tags
}

// GetSpecialChar is return chars (array type)
func GetSpecialChar() []string {
	chars := []string{
		">",
		"<",
		"\"",
		"'",
		"`",
		";",
		"|",
		"(",
		")",
		"{",
		"}",
		"[",
		"]",
		":",
		".",
		",",
		"+",
		"-",
		"=",
		"$",
	}
	return chars
}

// GetUsefulCode is return code list (array type)
func GetUsefulCode() []string {
	codes := []string{
		"javascript:",
		"JaVasCriPt:",
		"jaVas%0dcRipt:",
		"jaVas%0acRipt:",
		"jaVas%09cRipt:",
		"data:",
		"alert(",
		"alert`",
		"prompt(",
		"prompt`",
		"confirm(",
		"confirm`",
		"document.location",
		"document.cookie",
		"window.location",
	}
	return codes
}
