source 'https://rubygems.org'

gem "jekyll", "~> 4.3.3" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

# Theme
gem "just-the-docs"

# Plugins
group :jekyll_plugins do
  gem "jekyll-securitytxt"
  gem "jekyll-sitemap"
end
