---
name: dalfox
summary: Powerful open-source XSS scanner and utility focused on automation.
description: Dalfox is a powerful open-source tool that focuses on automation, making it ideal for quickly scanning for XSS flaws and analyzing parameters. Its advanced testing engine and niche features are designed to streamline the process of detecting and verifying vulnerabilities.
base: core22
grade: stable
confinement: strict
license: MIT
version: v2.12.0
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: i386

apps:
  dalfox:
    command: bin/dalfox
    plugs: [home, network, network-bind]

parts:
  dalfox:
    source: .
    plugin: rust
